Update checker
etianl/Trouser-Streak pull request #33
Opened 2024-03-01 09:37 UTC by Ogmur

self explanatory

2024-06-25 14:25 UTC, aaaasdfghjkllll commented
What the sigma

2024-09-16 00:21 UTC, RacoonDog requested changes

2024-09-16 00:21 UTC, RacoonDog commented on build.gradle
>  processResources {
configure `inputs.properties()`

2024-12-27 20:20 UTC, etianl commented
I am gonna close this with the excuse of us having a discord where we notify everyone of the new updates coming out. (I am actually still too lazy and silly to actually figure it out)
Discord: 
https://discord.gg/Az3G3p4ZCj

2024-12-27 20:20 UTC, closed without merging